include theos/makefiles/common.mk

TWEAK_NAME = ScreenPainterA
ScreenPainterA_FILES = Listener.xm
ScreenPainterA_LIBRARIES = activator
ScreenPainterA_FRAMEWORKS = UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
